<?php

/**
 * BasesimpletwitterUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $email
 * @property string $password
 * @property Doctrine_Collection $simpletwitterUsers
 * @property Doctrine_Collection $simpletwitterFollows
 * 
 * @method string              getName()                 Returns the current record's "name" value
 * @method string              getEmail()                Returns the current record's "email" value
 * @method string              getPassword()             Returns the current record's "password" value
 * @method Doctrine_Collection getSimpletwitterUsers()   Returns the current record's "simpletwitterUsers" collection
 * @method Doctrine_Collection getSimpletwitterFollows() Returns the current record's "simpletwitterFollows" collection
 * @method simpletwitterUser   setName()                 Sets the current record's "name" value
 * @method simpletwitterUser   setEmail()                Sets the current record's "email" value
 * @method simpletwitterUser   setPassword()             Sets the current record's "password" value
 * @method simpletwitterUser   setSimpletwitterUsers()   Sets the current record's "simpletwitterUsers" collection
 * @method simpletwitterUser   setSimpletwitterFollows() Sets the current record's "simpletwitterFollows" collection
 * 
 * @package    simpleTwitter
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesimpletwitterUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('simpletwitter_user');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 50,
             ));
        $this->hasColumn('email', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 50,
             ));
        $this->hasColumn('password', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('simpletwitterMessage as simpletwitterUsers', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('simpletwitterFollows', array(
             'local' => 'id',
             'foreign' => 'followed_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}