<?php

/**
 * BasesimpletwitterFollows
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $follower_id
 * @property integer $followed_id
 * @property simpletwitterUser $simpletwitterUser
 * 
 * @method integer              getFollowerId()        Returns the current record's "follower_id" value
 * @method integer              getFollowedId()        Returns the current record's "followed_id" value
 * @method simpletwitterUser    getSimpletwitterUser() Returns the current record's "simpletwitterUser" value
 * @method simpletwitterFollows setFollowerId()        Sets the current record's "follower_id" value
 * @method simpletwitterFollows setFollowedId()        Sets the current record's "followed_id" value
 * @method simpletwitterFollows setSimpletwitterUser() Sets the current record's "simpletwitterUser" value
 * 
 * @package    simpleTwitter
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesimpletwitterFollows extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('simpletwitter_follows');
        $this->hasColumn('follower_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('followed_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('simpletwitterUser', array(
             'local' => 'followed_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}