<?php

/**
 * simpletwitterFollowsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class simpletwitterFollowsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object simpletwitterFollowsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('simpletwitterFollows');
    }
}