<?php

/**
 * simpletwitterMessageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class simpletwitterMessageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object simpletwitterMessageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('simpletwitterMessage');
    }
}